packages:
  - "apps/*"
  - "packages/*"

minimumReleaseAge: 4320
minimumReleaseAgeStrict: true
minimumReleaseAgeIgnoreMissingTime: false
minimumReleaseAgeExclude: []

trustPolicy: no-downgrade
trustPolicyExclude:
  - nanoid
  - semver
trustLockfile: false

blockExoticSubdeps: true
strictDepBuilds: true
allowBuilds:
  better-sqlite3: true
  esbuild: true
dangerouslyAllowAllBuilds: false

verifyDepsBeforeRun: install
strictSsl: true
lockfile: true
